a=int(input("how many friend?"))
b=int(input("how many candy"))
share=(b // a)
remainder=(b%a)
print("You should give",share,"chocolates(s) to each friend and you will have",remainder,"left for you.")
quit()